id: I50A1829C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T22:32:55+00:00'
last_modified: '2022-06-08T03:23:42.055458+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W10736
  title: གསུང་འབུམ། པདྨ་དཀར་པོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    37B9:
      image_group_id: I1240
      title: ''
      total_pages: 758
      order: 1
      base_file: 37B9.txt
    204C:
      image_group_id: I1241
      title: ''
      total_pages: 626
      order: 2
      base_file: 204C.txt
    BC7C:
      image_group_id: I1242
      title: ''
      total_pages: 606
      order: 3
      base_file: BC7C.txt
    44AC:
      image_group_id: I1243
      title: ''
      total_pages: 504
      order: 4
      base_file: 44AC.txt
    A55A:
      image_group_id: I1244
      title: ''
      total_pages: 656
      order: 5
      base_file: A55A.txt
    DF86:
      image_group_id: I1245
      title: ''
      total_pages: 634
      order: 6
      base_file: DF86.txt
    0A55:
      image_group_id: I1246
      title: ''
      total_pages: 488
      order: 7
      base_file: 0A55.txt
    F86E:
      image_group_id: I1247
      title: ''
      total_pages: 702
      order: 8
      base_file: F86E.txt
    8A9B:
      image_group_id: I1248
      title: ''
      total_pages: 552
      order: 9
      base_file: 8A9B.txt
    1EDD:
      image_group_id: I1249
      title: ''
      total_pages: 614
      order: 10
      base_file: 1EDD.txt
    DD9E:
      image_group_id: I1250
      title: ''
      total_pages: 648
      order: 11
      base_file: DD9E.txt
    6A90:
      image_group_id: I1251
      title: ''
      total_pages: 604
      order: 12
      base_file: 6A90.txt
    7E7E:
      image_group_id: I1252
      title: ''
      total_pages: 656
      order: 13
      base_file: 7E7E.txt
    '6709':
      image_group_id: I1253
      title: ''
      total_pages: 610
      order: 14
      base_file: 6709.txt
    DE4E:
      image_group_id: I1254
      title: ''
      total_pages: 654
      order: 15
      base_file: DE4E.txt
    7BD6:
      image_group_id: I1255
      title: ''
      total_pages: 646
      order: 16
      base_file: 7BD6.txt
    39CB:
      image_group_id: I1256
      title: ''
      total_pages: 680
      order: 17
      base_file: 39CB.txt
    '7064':
      image_group_id: I1257
      title: ''
      total_pages: 680
      order: 18
      base_file: 7064.txt
    339D:
      image_group_id: I1258
      title: ''
      total_pages: 610
      order: 19
      base_file: 339D.txt
    C824:
      image_group_id: I1259
      title: ''
      total_pages: 578
      order: 20
      base_file: C824.txt
    18E2:
      image_group_id: I1260
      title: ''
      total_pages: 612
      order: 21
      base_file: 18E2.txt
    E1C2:
      image_group_id: I1261
      title: ''
      total_pages: 640
      order: 22
      base_file: E1C2.txt
    '6448':
      image_group_id: I1262
      title: ''
      total_pages: 652
      order: 23
      base_file: 6448.txt
    '8788':
      image_group_id: I1263
      title: ''
      total_pages: 612
      order: 24
      base_file: 8788.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
