id: P005481
initial_creation_type: ocr
source_metadata:
  id: bdr:W10736
  title: གསུང་འབུམ། པདྨ་དཀར་པོ
  author: ''
  volumes:
    e873ca7818354838bf86aea295e31581:
      image_group_id: I1240
      title: ''
      volume_number: 1
      total_pages: 758
      base_file: v001.txt
    094de25020e74b5c99fec654c6582900:
      image_group_id: I1241
      title: ''
      volume_number: 2
      total_pages: 626
      base_file: v002.txt
    31fb7e8a455c48d6a5ff4b18509341d7:
      image_group_id: I1242
      title: ''
      volume_number: 3
      total_pages: 606
      base_file: v003.txt
    63a86193d77d48fbb911e64b30c1977f:
      image_group_id: I1243
      title: ''
      volume_number: 4
      total_pages: 504
      base_file: v004.txt
    b49ba9f392d84dec88a30e4243d21af5:
      image_group_id: I1244
      title: ''
      volume_number: 5
      total_pages: 656
      base_file: v005.txt
    cfca21c13eae49d68c6567139b7b815f:
      image_group_id: I1245
      title: ''
      volume_number: 6
      total_pages: 634
      base_file: v006.txt
    aba72fadd9d54826aa9bdf4fb9595f31:
      image_group_id: I1246
      title: ''
      volume_number: 7
      total_pages: 488
      base_file: v007.txt
    a619b2ed5d1f432baa42d044e5f163cc:
      image_group_id: I1247
      title: ''
      volume_number: 8
      total_pages: 702
      base_file: v008.txt
    58bac6770a31414483004ab6548c063b:
      image_group_id: I1248
      title: ''
      volume_number: 9
      total_pages: 552
      base_file: v009.txt
    04c8cbdbee42468aa770a52275e3df56:
      image_group_id: I1249
      title: ''
      volume_number: 10
      total_pages: 614
      base_file: v010.txt
    62c2f9f2bdac42a887a948ae53ab6118:
      image_group_id: I1250
      title: ''
      volume_number: 11
      total_pages: 648
      base_file: v011.txt
    29b86c438d0d40bab54bc7695815bf11:
      image_group_id: I1251
      title: ''
      volume_number: 12
      total_pages: 604
      base_file: v012.txt
    7184662debed4398ae22bc99e3c92cfa:
      image_group_id: I1252
      title: ''
      volume_number: 13
      total_pages: 656
      base_file: v013.txt
    e09d198a5fc941fb801667a00c045892:
      image_group_id: I1253
      title: ''
      volume_number: 14
      total_pages: 610
      base_file: v014.txt
    1fabb117c7e74f8987e219061a22d940:
      image_group_id: I1254
      title: ''
      volume_number: 15
      total_pages: 654
      base_file: v015.txt
    8b870a061fbc42c097d37cb4aaaf0a52:
      image_group_id: I1255
      title: ''
      volume_number: 16
      total_pages: 646
      base_file: v016.txt
    43a87d67cc4d424e8c432780c29e643a:
      image_group_id: I1256
      title: ''
      volume_number: 17
      total_pages: 680
      base_file: v017.txt
    a8da90e5256442759f6bab619e4ad6c3:
      image_group_id: I1257
      title: ''
      volume_number: 18
      total_pages: 680
      base_file: v018.txt
    cbecbed7315c4be7bc35b5f0148bb660:
      image_group_id: I1258
      title: ''
      volume_number: 19
      total_pages: 610
      base_file: v019.txt
    3be7ae9cf65f451f9a3e31c474ad8092:
      image_group_id: I1259
      title: ''
      volume_number: 20
      total_pages: 578
      base_file: v020.txt
    fc44b306a1d34ba68f6d1042e4a615c9:
      image_group_id: I1260
      title: ''
      volume_number: 21
      total_pages: 612
      base_file: v021.txt
    65048255dae343a88672b483ce033113:
      image_group_id: I1261
      title: ''
      volume_number: 22
      total_pages: 640
      base_file: v022.txt
    787c737e969a4eb0a1607f9bb7472828:
      image_group_id: I1262
      title: ''
      volume_number: 23
      total_pages: 652
      base_file: v023.txt
    df4e2ce618a54ef1929608dbe6134b07:
      image_group_id: I1263
      title: ''
      volume_number: 24
      total_pages: 612
      base_file: v024.txt
